# Imagen base de Golang
FROM golang:latest

# Directorio de trabajo
WORKDIR /app

# Copiar el código fuente al contenedor
COPY . .

RUN go mod tidy
RUN go mod download
# Compilar la aplicación
RUN go build -o main .

# Exponer el puerto
EXPOSE 8080

# Comando para ejecutar la aplicación
CMD ["./main"]
