# Utiliza una imagen base de Golang
FROM golang:latest

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia el código fuente de tu servicio de escritura al contenedor
COPY write-service/ .
#COPY internal/write internal/write

RUN go mod tidy
RUN go mod download

# Compila tu servicio de escritura
RUN go build -o write-service main.go

# Expone el puerto en el que se ejecuta tu servicio
EXPOSE 8080

# Ejecuta tu servicio de escritura cuando se inicie el contenedor
CMD ["./write-service"]
